### ISSUE TITLE
Add proxy support for download of pre-built binaries

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-native-metrics#124]
## Is your feature request related to a problem? Please describe.

A customer's CI environment does not allow raw web requests out to get binaries and their environment is not setup to compile. While they may be able to get compilation working, allowing a download via proxy would be preferred/more straight-forward for them.

## Feature Description

Add the ability to define and connect via proxy for download of pre-built binary.

I'm guessing we'd likely do this via ENV configuration plus implementation similar to what we do in the main agent.

**Comment by michaelgoin** [comment]
As it turns out, but default node-gyp will make a web request to get Node headers. So in this identical situation, native complication doesn't "just work" but requires additional lifting.

**Comment by bizob2828** [comment]
You can use this to test the proxy locally https://github.com/bizob2828/node-proxy-server

**Comment by garbados** [comment]
Since we host binaries on Github Releases, wouldn't this be Github's problem? By which I mean: how do we provide a download path that permits access via proxy when we don't control the download servers? Should we provide an alternate download location, and if so, what are the functional requirements of such a solution?

**Comment by michaelgoin** [comment]
@garbados We host these pre-built downloads on our download server (conceptually). Regardless, this install happens as a part of an npm install executed script. It first attempts to compile locally and then falls back to download. This download request is what is being requested to go through a proxy as arbitrary network paths may (often are not) allowed from containerized environments.

https://github.com/newrelic/node-native-metrics/blob/44ddead0ab09611c8609069eef67b768282c3f62/lib/pre-build.js#L206
