### ISSUE TITLE
Inclusion of 'upload' in pre-build.js leveraging aws-sdk can cause issues

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-native-metrics#125]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

As a general level-set... scripts intended for our own use only shouldn't be shipped with the module. In this case, most of the pre-build is used for install but the 'upload' part is not.

This also causes issues for applications created using `create-react-app`. 

For some reason (looks like optimization based on the output?) it attempts to 'build' our script and fails because the aws-sdk is not installed. This is not normally a problem, because it is not used unless we've installed as a dev dependency in our CI but is appearing as a problem here.

While there will likely be other issues once this is resolved, we should try to extract the upload portion so we also aren't shipping code not intended for customer use and maybe avoid issues with other frameworks.

```sh
> react-scripts build

Creating an optimized production build...
Failed to compile.

./node_modules/@newrelic/native-metrics/lib/pre-build.js
Cannot find module: 'aws-sdk'. Make sure this package is installed.
```

## Steps to Reproduce
```sh
npx create-react-app my-app
cd my-app && npm i newrelic
npm run build
```

**Comment by bizob2828** [comment]
FWIW I could not reproduce this error. I was using the name version of `react-scripts`. I did open PR to decouple upload logic with the rest.  Waiting for @michaelgoin to push the repo where he can reproduce this issue

**Comment by bizob2828** [comment]
I verified this was no longer an issue by running `npm link` from the branch of this fix and linked it in my create react app and I no longer get the aws-sdk error 🎉
