### ISSUE TITLE
Permission denied for mkdir .node-gyp with installing the package globally

### ISSUE THREAD

**Issue by eugeneievlev** [newrelic/node-native-metrics#126]
## Description

Getting permission errors while installing a NewRelic node.js agent (with the global option enabled) into node:12.16.3-alpine docker container.
Docker version 19.03.13-ce, build 4484c46

```
[root@d48cf4f2cb51 app]# npm install -g newrelic --save;
/usr/local/bin/newrelic-naming-rules -> /usr/local/lib/node_modules/newrelic/bin/test-naming-rules.js

> @newrelic/native-metrics@6.0.0 install /usr/local/lib/node_modules/newrelic/node_modules/@newrelic/native-metrics
> node ./lib/pre-build.js install native_metrics

============================================================================
Attempting install in native-metrics module. Please note that this is an
OPTIONAL dependency, and any resultant errors in this process will not
affect the general performance of the New Relic agent, but event loop and
garbage collection metrics will not be collected.
============================================================================

> /usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean configure
gyp WARN EACCES current user ("nobody") does not have permission to access the dev dir "/root/.cache/node-gyp/12.16.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/newrelic/node_modules/@newrelic/native-metrics/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/newrelic/node_modules/@newrelic/native-metrics/.node-gyp'
gyp ERR! System Linux 4.14.138-89.102.amzn1.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean" "configure"
gyp ERR! cwd /usr/local/lib/node_modules/newrelic/node_modules/@newrelic/native-metrics
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
Failed to execute native-metrics install: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/newrelic/node_modules/@newrelic/native-metrics/build'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @newrelic/native-metrics@6.0.0 (node_modules/newrelic/node_modules/@newrelic/native-metrics):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @newrelic/native-metrics@6.0.0 install: `node ./lib/pre-build.js install native_metrics`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ newrelic@7.3.1
updated 1 package in 3.623s
```

**Comment by carlo-808** [comment]
@eugeneievlev Thank you for submitting the bug. I'm curious as to why are you installing the agent globally? In most use cases I've seen, the agent is installed per application. That way, you can install the agent and the native metrics module outside of docker than copy the app with the `node_modules` directory into the docker container.

**Comment by eugeneievlev** [comment]
Hey @carlo-808, thank you for your reply!
I'm trying to do so due to the deployment optimisation purposes. I think about the possibility to avoid the installation of all packages (especially those that don't relate to app functionality). So the idea was to install everything that is not app-related to the container, so you will need to build the only app-related modules while everything extra already in the container.
Regards,
Eugene

**Comment by carlo-808** [comment]
Hi @eugeneievlev, apologies for the late reply, are you still having an issue with the native-metrics install? We generally do not recommend installing the Node agent globally. This does seem like a permissions issue on your machine with your end user not having access to the build tooling. It is unlikely an issue with the agent. If you are still having issues, please reach out to [New Relic Support](https://github.com/newrelic/node-newrelic#support).
