### ISSUE TITLE
Remove no-longer used CPU code

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-native-metrics#154]
The agent now uses the built-in CPU measurements, for the pure CPU metrics instead of the native module.

Since we support a minimum version of Node 12, there are no longer any supported cases where the the native module CPU (non loop) metrics will be used.

https://github.com/newrelic/node-newrelic/blob/main/lib/sampler.js#L198-L207

Might as well rip the code-fork out of the agent, as well.

Effort: Small

**Comment by bizob2828** [comment]
Moving this back as the code in agent still needs to be ripped out
