### ISSUE TITLE
Break down `lib/pre-build` into their respective actions

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-native-metrics#157]
## Is your feature request related to a problem? Please describe.
We've had two obscure errors that required fixes in `lib/pre-build.js`, #155 and #125.  The former affected running applications which is very concerning.  To avoid toil we `lib/pre-build` should be further broken down based on the discrete actions.

## Feature Description
Refactor code into `load`, `install`, and `build`

## Additional context
Install, build, download are tightly coupled but through some refactor it can be broken down into reusable helpers.  At the very least `load` should be its own file as all it does is require the module and none of the code in `lib/pre-build` isn't really needed.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Really Want]

**Comment by rr0214** [comment]
Effort: Medium
