### ISSUE TITLE
Fix download integration test

### ISSUE THREAD

**Issue by bizob2828** [newrelic/node-native-metrics#160]
## Is your feature request related to a problem? Please describe.
In https://github.com/newrelic/node-native-metrics/pull/147 we added integration tests to avoid failures in the `lib/pre-build`.  It was overlooked in the download case that it attempts to download a version based on the package.json version.  When a new version is pushed to main the pre-built does not yet exist in AWS so this test fails.

## Feature Description
We could symlink "latest" for every architecture and try to always download this.  Alternatively we could only run this test in PRs.

## Additional Context
The test is now skipped https://github.com/newrelic/node-native-metrics/pull/159/files until it can be resolved with this issue.  We added support for download via http proxy #178.  We should try to do the work at the same time and only run the proxy test on release and both normal and proxy download in PRs, merges to main, etc

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Must Have]

**Comment by rr0214** [comment]
Effort: Small

**Comment by bizob2828** [comment]
I'm working on this with #178

**Comment by bizob2828** [comment]
Addressed in https://github.com/newrelic/node-native-metrics/pull/186
