### ISSUE TITLE
Tests fail on Arm64 machines with Node.js 14 and 16 

### ISSUE THREAD

**Issue by garbados** [newrelic/node-native-metrics#164]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

Running the test suite against Arm64 fails on Node.js 14 and 16: https://github.com/newrelic/node-native-metrics/runs/3626817626?check_suite_focus=true

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

The Arm64 CI job uses https://github.com/uraimo/run-on-arch-action/blob/master/src/run-on-arch.sh to run an Arm64 system within a container. This level of indirection seems to cause problems. 

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

Tests should pass on Arm64 machines for all current versions of Node.js.

**Comment by garbados** [comment]
For reference, using a local Docker installation to create a virtual Arm64 machine, I was unable to reproduce this issue. Tests passed normally. I believe the issue is specific to the GitHub action we chose to use.

**Comment by michaelgoin** [comment]
Replacing with: https://github.com/newrelic/node-native-metrics/issues/205 as a proper contained effort.
