### ISSUE TITLE
Add ARM 64 test runs and pre-built downloads

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-native-metrics#205]
Looks like there are some well defined docker patterns out for this now with GHA.

It would be good to get the test coverage running and working in place and have pre-builts for download on the download site.

Some poking around has been done with this PR but was non functional in GHA: https://github.com/newrelic/node-native-metrics/pull/163. See also: https://github.com/newrelic/node-native-metrics/issues/164.

**Comment by jsumners-nr** [comment]
I have been researching this issue and have found the following thus far:

1. https://github.com/jsumners-nr/native-add/tree/491b7c80b490c2f9d55bf958ff79c91981ff73da shows a project based on `prebuildify` and a [n-api based addon](https://nodejs.org/api/n-api.html). The result of the CI pipeline in that branch is an npm package that includes linux x64, linux arm64, windows x86/x64, and macos arm64 native binaries included in the package. When the module is used in a script, it loads the appropriate native binary.
2. We cannot convert `@newrelic/native-metrics` to a n-api based module. The [V8 GC API](https://github.com/nodejs/nan/blob/e14bdcd1f72d62bca1d541b66da43130384ec213/doc/v8_internals.md) utilized by this module does not have an equivalent API in core n-api nor in the [node-addon-api](https://github.com/nodejs/node-addon-api/) wrapper.
3. It is _possible_ that we could eliminate utilizing a native module altogether by utilizing the [perf_hooks api](https://nodejs.org/api/perf_hooks.html#garbage-collection-gc-details). But it is unclear to me if we'd have a sufficient resolution on the metrics. The native API is calculating statistics via a running total fed by a callback invoked by V8 when the garbage collector runs. The `perf_hooks` method _may_ be doing the same under the hood, but I'm not sure if we get the same information. An experiment would need to be conducted.
4. We can use `prebuildify` to accomplish the asks in this issue, but it will mean running the compile for every platform we intend to support across all versions of Node.js that we intend to support (as opposed to once per platform with n-api).

My next course of action is to create a new branch in the project linked on item 1 that will build a non-n-api module across multiple versions of Node.js and platforms to work out what would need to be done here.
