### ISSUE TITLE
Fix npm install newrelic --save

### ISSUE THREAD

**Issue by wgohier** [newrelic/node-native-metrics#212]
## Description

Can't install npm newrelic package due to a code error in package

## Steps to Reproduce

npm install newrelic --save

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\@newrelic\native-metrics\lib\pre-build.js:135
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

## Your Environment

- windows 11
- npm 6.4.1
- node 8.12.0

## Additional context

Error on line 135 in node-native-metrics\lib\pre-build.js:135

`} catch {`

instead of 

`} catch ( error ) {`

**Comment by bizob2828** [comment]
@wgohier this package and the agent(newrelic) no longer supports Node 8.  It was dropped 2 years ago.  If you still need to use Node.js, which I do no recommend as it is no longer supported, you can downgrade to `newrelic@6.14.0`

**Comment by jordigh** [comment]
The syntax is valid, at least in later node versions.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#syntax

Unfortunately, the earliest node version we support is 14. While we could possibly patch this file to be parsed by node 8, you will encounter many other problems besides this one.

If you are required to stay on node 8, the last version of the agent that supported node 8 was [agent version 6](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/installation-configuration/update-nodejs-agent/#node-support-v6). We recommend, however, that you update your node version if at all possible.

**Comment by wgohier** [comment]
OK. Thank you  for your answers and recommandations.
