### ISSUE TITLE
Unable to download prebuilts on v10 of native-metrics

### ISSUE THREAD

**Issue by jstaro** [newrelic/node-native-metrics#233]
We're trying to move to Node.js 20(.6.0) since it will be LTS in a month and we have currently have to add Python and node-gyp packages to our x64 and arm64 Docker images to build this module (and `inspect-fn`).

Would it be possible to add pre-built binaries here?

**Comment by bizob2828** [comment]
Hi @jstaro we do provide prebuilts on Node 20 for x86_64.  We have never provided arm64 prebuilts but there's a feature request for that #205.  You also mentioned @contrast/inspect-fn which also appears to have a prebuilt for x86_64 and arm64 on Node 20 as of 3.4.0.  Are you trying using v10.0.0 of `@newrelic/native-metrics`?

**Comment by jstaro** [comment]
```
Download error: ENOENT: no such file or directory, open '/app/node_modules/@newrelic/native-metrics/build/Release/_newrelic_native_metrics-10_0_0-native_metrics-115-linux-x64.node', falling back to build
```

from `yarn.lock`:
```
newrelic@^11.0.0:
  version "11.0.0"
  resolved "https://registry.yarnpkg.com/newrelic/-/newrelic-11.0.0.tgz#71ee78b1e4f31461131e1cf1f86deb67642812a6"
  integrity sha512-uZEetgjfoscuuFNP7TH5BIKLv4vnfX27DV9y+Yb26ZrC3CNnVL+jBOAKY4+/vTxQiQHCi4uPfRyjw+1/3fOQXA==
  dependencies:
    "@grpc/grpc-js" "^1.8.10"
    "@grpc/proto-loader" "^0.7.5"
    "@newrelic/aws-sdk" "^7.0.0"
    "@newrelic/koa" "^8.0.0"
    "@newrelic/security-agent" "0.2.1"
    "@newrelic/superagent" "^7.0.0"
    "@tyriar/fibonacci-heap" "^2.0.7"
    concat-stream "^2.0.0"
    https-proxy-agent "^7.0.1"
    import-in-the-middle "^1.4.2"
    json-bigint "^1.0.0"
    json-stringify-safe "^5.0.0"
    readable-stream "^3.6.1"
    require-in-the-middle "^7.2.0"
    semver "^7.5.2"
    winston-transport "^4.5.0"
  optionalDependencies:
    "@contrast/fn-inspect" "^3.3.0"
    "@newrelic/native-metrics" "^10.0.0"
    "@prisma/prisma-fmt-wasm" "^4.17.0-16.27eb2449f178cd9fe1a4b892d732cc4795f75085"
```

Perhaps I am missing something. This worked fine before on Node.js 16.

**Comment by bizob2828** [comment]
@jstaro I just tried on a new app on linux and it worked just fine.  

```sh
native-metrics/build/Release
❯ ls
_newrelic_native_metrics-10_0_0-native_metrics-115-linux-x64.node
```

Can you try removing the yarn.lock and try to `npm i newrelic@latest`?

**Comment by jstaro** [comment]
Certainly. I'm afraid that didn't help.

More relevant data points:
- We see this on CircleCI, docker build using `node:20-alpine`. It's a multi-stage build with a 12-line Dockerfile so no funny business. I can share the Dockerfile if you need.
- On my local Ubuntu machine it works fine. On my local Windows machine, I have to have `node-gyp`, Python and C++ tools installed. That's fine, I get that. No pre-built binaries there.
- On that same local developer machine with abovementioneed docker build, it fails in the same way.
- However, a docker build with `node:16-alpine` and `newrelic@10` on that same machine works absolutely fine.

**Comment by jstaro** [comment]
Worth noting that `npm` makes its darndest to hide that this is happening. You can only see that something is up with `--verbose`.

**Comment by bizob2828** [comment]
Ok, I traced this down.  It's a bug but for all Node.js prebuilds on v10. A PR is coming shortly.

**Comment by jstaro** [comment]
@bizob2828 Wonderful, thanks! Verified to work on our end.
