### ISSUE TITLE
Error: Module did not self-register

### ISSUE THREAD

**Issue by frankda** [newrelic/node-native-metrics#258]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
Hi I got error:
```
✖ Error: Module did not self-register: '/Users/[project-root]/node_modules/@newrelic/native-metrics/prebuilds/darwin-arm64/@newrelic+native-metrics.abi115.uv1.armv8.glibc.node'.
```
After upgrade node version from 16 to 20. Tried `npm rebuild` but doesn't work. According to this post https://github.com/nodejs/node/issues/21783#issuecomment-429637117, it might resolve this issue. Could you please consider update according to this post?

Meanwhile, I will try to pull and build the module myself with solution and see if it can fix this issue.

## Expected Behavior

Sorry I cannot provide more information as I am new to newrelic and I don't know how to reproduce with a minimal reproducible example. 

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Node version: 20.11.1
* ex: Operating System and version:
      System Version: macOS 14.2 (23C64)
      Kernel Version: Darwin 23.2.0

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by mrickard** [comment]
Thank you for reporting this, @frankda . Would you be able to provide us with a repro case with which we can test?

**Comment by frankda** [comment]
> Thank you for reporting this, @frankda . Would you be able to provide us with a repro case with which we can test?

Please find this repo https://github.com/frankda/newrelic-native-metrics-context-aware-example for minimal reproducible example when use @newrelic/native-metrics in multiple node worker thread. Will get `Error: Module did not self-register`

We encounter this issue when using native-metrics with serverless framework and serverless-offline plugin. Don't have this issue with node v16 and older version of serverless. I suspect newer serverless-offline is using worker thread and native-metrics is not [context aware](https://github.com/nodejs/node/blob/main/doc/api/addons.md#context-aware-addons).

I can create a PR for this if needed

**Comment by mrickard** [comment]
You're certainly welcome to open a PR, though I should note that [we don't recommend enabling the native metrics plugin when operating in Serverless Mode](https://github.com/newrelic/node-newrelic/blob/7b3c8d1445ea9876b36eda31d979dac9b65dad14/lib/config/index.js#L1140-L1170), and as of v11, [we don't recommend running the agent in worker threads](https://github.com/newrelic/node-newrelic/blob/7b3c8d1445ea9876b36eda31d979dac9b65dad14/lib/config/default.js#L1334-L1348).

**Comment by bizob2828** [comment]
I'm going to close this based on @mrickard comments. However, @frankda feel free to open PR to address your suggestion
