### ISSUE TITLE
Minimal code cleanup

### ISSUE THREAD

**Issue by carlonewrelic** [newrelic/node-native-metrics#80]
We are already in decent shape but do a pass for general things outlined in the Engineering Plan.

Helpful regex:

```
rg --pcre2 '(?<!SELECT)(// |^ *\*(?!/))(?! Copyright|.*Apache|.*eslint)'
```

**Comment by michaelgoin** [comment]
Nothing of concern, as expected.

One thing I will call out is there is a ton of email attributed TODO's form the gtest code pulled in. Since that's going to have been in the original code, I'm leaving it but those will likely pop up in the security scan, etc.
