### ISSUE TITLE
Switch to 'main' as default branch

### ISSUE THREAD

**Issue by carlonewrelic** [newrelic/node-native-metrics#84]
We've settled on main as the new default branch name.

This will involve creating and migrating to the new branch before deleting the prior. We'll also want to ensure we change the base of any existing PR's etc.

Hanselman has some helpful instructions on the blog: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx. I'm sure there are other useful resources out there as well.

- Change the base of all open PRs (**do this first or risk auto-closing when change default**)
- Change default branch in repo settings
- Copy master branch protection rules to main
- Setup Snyk to use main
- Edit any release documents to reference main instead of master (sometimes recommend doing via separate PR to exercise snyk/etc on new branch).
- Delete master branch once all good.

**Comment by michaelgoin** [comment]
going to delete master branch later in project (maybe once merge to main or after deploy) just in case there's a surprise of something needing it in this project.
