### ISSUE TITLE
Make Third Party Notices updateable via standard CLI tool

### ISSUE THREAD

**Issue by carlonewrelic** [newrelic/node-native-metrics#85]
* Make updateable by the standard CLI tool to make easier and help prevent misses.
* Ensure current notices up to date. (expect at least the agent to update). We may want to set the minimum to the latest as we converge these on open source.

https://github.com/newrelic/newrelic-oss-cli#third-party-notice-generation-for-npm-based-projects

**Comment by michaelgoin** [comment]
heads-up... looks like we have come google unit test runner code pulled in that has licenses at the top of the files. not sure if legal will want this represented in teh third party notices and if they do, how that should look.

**Comment by michaelgoin** [comment]
Looks like the footer requirement didn't make it into this issue. Will grab from different issue and add here for reference.

**Comment by michaelgoin** [comment]
This needs to be added to the bottom of the third party notices.

```
-----

Portions copyright Node.js contributors. Depending on your existing libraries and package management settings,
your systems may call externally maintained libraries in addition to those listed above.
See [here](https://nodejs.org/en/docs/meta/topics/dependencies/) and [here](https://github.com/nodejs/node/blob/v4.3.1/LICENSE)
for additional details regarding externally maintained libraries and certain related licenses and notices.”
```
